// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiKIqcWA4YuPcZ6Xl3k4VS2GoFTsDDR5c',
    appId: '1:406530303265:web:e9c70e3fa43cea3443ca60',
    messagingSenderId: '406530303265',
    projectId: 'zad-alkhair-app',
    authDomain: 'zad-alkhair-app.firebaseapp.com',
    storageBucket: 'zad-alkhair-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdXGbmwbHC07FVFCzKuZREBuKUGokErw8',
    appId: '1:406530303265:android:d031d9d3f8e906aa43ca60',
    messagingSenderId: '406530303265',
    projectId: 'zad-alkhair-app',
    storageBucket: 'zad-alkhair-app.firebasestorage.app',
  );

  // الويندوز بيستخدم إعدادات تطبيق الويب نفسه (هيك بيولّدها FlutterFire CLI).
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiKIqcWA4YuPcZ6Xl3k4VS2GoFTsDDR5c',
    appId: '1:406530303265:web:e9c70e3fa43cea3443ca60',
    messagingSenderId: '406530303265',
    projectId: 'zad-alkhair-app',
    authDomain: 'zad-alkhair-app.firebaseapp.com',
    storageBucket: 'zad-alkhair-app.firebasestorage.app',
  );
}
